-- ==============================================================================
-- ARM Stage 6 Migration: AI Report Planner
-- Creates report_plans table with structured JSONB storage, audit metadata,
-- foreign keys, performance indexes, and strict Row Level Security.
-- Preserves all Stages 1-5 schemas without breaking changes.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.report_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    template_id UUID NOT NULL REFERENCES public.templates(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    template_schema_version TEXT NOT NULL DEFAULT '1.0.0',
    project_updated_at TIMESTAMPTZ DEFAULT NULL,
    planner_version TEXT NOT NULL DEFAULT '1.0.0',
    ai_provider TEXT NOT NULL DEFAULT 'gemini',
    ai_model TEXT NOT NULL DEFAULT 'gemini-3.1-flash-lite',
    status TEXT NOT NULL DEFAULT 'completed',
    plan_json JSONB NOT NULL,
    summary_metrics JSONB DEFAULT '{}'::jsonb,
    is_approved BOOLEAN DEFAULT FALSE,
    approved_at TIMESTAMPTZ DEFAULT NULL,
    approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ DEFAULT now()
);

-- Status check constraint
ALTER TABLE public.report_plans DROP CONSTRAINT IF EXISTS chk_report_plans_status;
ALTER TABLE public.report_plans ADD CONSTRAINT chk_report_plans_status
    CHECK (status IN ('draft', 'planning', 'completed', 'approved', 'failed', 'stale'));

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_report_plans_project_id ON public.report_plans(project_id);
CREATE INDEX IF NOT EXISTS idx_report_plans_template_id ON public.report_plans(template_id);
CREATE INDEX IF NOT EXISTS idx_report_plans_user_id ON public.report_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_report_plans_status ON public.report_plans(status);
CREATE INDEX IF NOT EXISTS idx_report_plans_created_at ON public.report_plans(created_at DESC);

-- Enable RLS
ALTER TABLE public.report_plans ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Users can manage report plans for their own projects" ON public.report_plans;
DROP POLICY IF EXISTS "Service role can manage all report plans" ON public.report_plans;

-- RLS policies
CREATE POLICY "Users can manage report plans for their own projects"
    ON public.report_plans
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.projects p
            WHERE p.id = report_plans.project_id
            AND (p.user_id = auth.uid() OR p.owner_id = auth.uid())
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.projects p
            WHERE p.id = report_plans.project_id
            AND (p.user_id = auth.uid() OR p.owner_id = auth.uid())
        )
    );

CREATE POLICY "Service role can manage all report plans"
    ON public.report_plans
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Comments
COMMENT ON TABLE public.report_plans IS 'Stage 6: Authoritative structured report plans generated by the AI Report Planner';
COMMENT ON COLUMN public.report_plans.plan_json IS 'Validated ReportPlan JSON document adhering to TemplateSchema constraints and project facts';
COMMENT ON COLUMN public.report_plans.template_schema_version IS 'Schema version of the Stage 4 locked template';
COMMENT ON COLUMN public.report_plans.project_updated_at IS 'Project modification timestamp at planning time for stale plan detection';
